repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/lorenzwalthert/pre-commit-hooks
    rev: v0.4.3.9013
    hooks:
    -   id: lintr
    -   id: roxygenize
        additional_dependencies:
        - dplyr
        - forcats
        - ggplot2
        - tidyr
        - data.table
        - scales
