# Test Harness for Cost Calculation

# This script is designed to be run from the root of the project directory.
# It loads a sample of the population data and the necessary cost coefficients,
# then calls the calculate_costs_fcn to generate a "golden master"
# output for characterization testing.

# --- 1. Load Packages and Functions ---
library(here)
library(arrow)
library(yaml)
source(here("R", "calculate_costs_fcn.R"))
source(here("R", "config_loader.R"))

# --- 2. Load Data ---
# Load the initial attribute matrix for a specific year
am_file <- here("input", "population", "mysim_public.csv")
if (!file.exists(am_file)) {
  stop("Required input file not found: ", am_file)
}
attribute_matrix <- read.csv(am_file)

# --- 3. Load Coefficients ---
# The cost function requires the 'costs' parameters, which are part of the main
# coefficients file.
model_coefficients <- load_config(here("config", "coefficients.yaml"))
cost_params <- model_coefficients$coefficients$costs

# --- 4. Run the Function Under Test ---
# Execute the function to get the result based on the current implementation.
result_matrix <- calculate_costs_fcn(attribute_matrix, cost_params)

# --- 5. Save the "Golden Master" Output ---
# This file serves as the baseline for our characterization test.
# We will save the relevant cost columns.
output_dir <- here("tests", "testthat", "fixtures")
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

# Select only the columns generated by the costs function for the golden master
cost_columns <- c("cycle_cost_healthcare", "cycle_cost_patient", "cycle_cost_societal", "cycle_cost_total")
golden_master_data <- result_matrix[, cost_columns, with = FALSE]

write.csv(golden_master_data,
          file.path(output_dir, "golden_master_costs.csv"),
          row.names = FALSE)

print("Test harness for costs executed successfully. Golden master file created.")
