# config/interventions.yaml

# --- Intervention Modelling Configuration ---

enabled: true

interventions:
  # --- Intervention 1: Public Health Campaign for BMI Reduction ---
  public_health_campaign_bmi:
    type: "bmi_modification"
    start_year: 2028
    end_year: 2038

    # Target population defines who the intervention applies to.
    # An empty field means it applies to everyone.
    # Conditions are combined with AND.
    target_population:
      min_age: 45
      max_age: 65
      # sex: "[1] Male" # Example: can also target by sex
      # year12: 0 # Example: can also target by SES (0 = low, 1 = high)

    parameters:
      # This intervention reduces BMI by a certain amount.
      # A negative value would represent an increase.
      bmi_change: -0.5
      # Uptake rate represents the proportion of the target population
      # that is affected by the intervention each year.
      uptake_rate: 0.10 # 10% of the target pop is affected

  # --- Intervention 2: New Advanced OA Drug ---
  new_oa_drug:
    type: "qaly_and_cost_modification"
    start_year: 2030
    end_year: 2040

    target_population:
      # This drug is for patients with moderate to severe OA
      min_kl_grade: 3 # Targets KL grades 3 and 4

    parameters:
      # This intervention provides a direct QALY improvement but also has a cost.
      qaly_gain: 0.05 # Annual improvement in health utility
      annual_cost: 2500 # Annual cost of the drug per person
      uptake_rate: 0.50 # 50% of eligible patients use the drug

  # --- Intervention 3: Improved Surgical Technique for TKA ---
  improved_tka_technique:
    type: "tka_risk_modification"
    start_year: 2025
    end_year: 2045

    target_population:
      # This intervention affects anyone receiving a TKA
      min_kl_grade: 2 # TKA can happen from KL grade 2 onwards

    parameters:
      # This intervention reduces the probability of needing a TKA by a relative amount.
      # A value of 0.8 means a 20% reduction in risk.
      tka_risk_multiplier: 0.80
      uptake_rate: 0.75 # 75% of surgeons adopt the new technique
