# Generated by Gemini. This file is used to declare global variables to
# avoid "no visible binding for global variable" notes from R CMD check.
utils::globalVariables(c(
  "age", "age_cat", "agetka1", "bmi", "bmi_over30", "bmi_under30", "d_bmi",
  "dead", "drugoa", "female", "kl_score", "male", "oa", "oa_initiation_prob",
  "public", "qx", "rev1", "rev_haz_early", "rev_haz_late", "rev_lpv", "rev_prob",
  "rev_prob_early", "rev_prob_late", "revi", "sex", "tkai", "tkai_backup"
))
