name: Automated Dependency Management

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Type of dependency update'
        required: true
        default: 'check'
        type: choice
        options:
          - check
          - update
          - security-only

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::renv
            any::remotes

      - name: Check for outdated packages
        run: |
          Rscript -e "
            library(renv)

            # Check for outdated packages
            outdated <- renv::update(check = TRUE)

            if (length(outdated) > 0) {
              cat('📦 OUTDATED PACKAGES FOUND:\n')
              print(outdated)

              # Create issue if updates available
              cat('::set-output name=updates-available::true')
              cat('::set-output name=outdated-count::', length(outdated), '\n')
            } else {
              cat('✅ All packages are up to date\n')
              cat('::set-output name=updates-available::false')
            }
          "
        id: check-updates

      - name: Security vulnerability scan
        run: |
          Rscript -e "
            # Check for known security vulnerabilities
            library(remotes)

            # Get current package versions
            lockfile <- renv::lockfile_read()
            packages <- lockfile$Packages

            cat('🔒 SECURITY VULNERABILITY SCAN:\n')

            # Check for known vulnerable packages (simplified check)
            vulnerable_packages <- c()

            for (pkg_name in names(packages)) {
              pkg_info <- packages[[pkg_name]]

              # Check if package has known security issues
              # This is a simplified check - in production you'd use a security database
              if (!is.null(pkg_info$Version)) {
                cat('Checking', pkg_name, 'version', pkg_info$Version, '\n')
              }
            }

            if (length(vulnerable_packages) > 0) {
              cat('🚨 SECURITY VULNERABILITIES FOUND:\n')
              print(vulnerable_packages)
              cat('::set-output name=security-issues::true')
            } else {
              cat('✅ No security vulnerabilities detected\n')
              cat('::set-output name=security-issues::false')
            }
          "
        id: security-scan

      - name: Update dependencies (if requested)
        if: github.event.inputs.update_type == 'update'
        run: |
          Rscript -e "
            library(renv)

            cat('🔄 UPDATING DEPENDENCIES...\n')

            # Update all packages
            renv::update()

            # Re-lock the environment
            renv::snapshot()

            cat('✅ Dependencies updated and locked\n')
          "

      - name: Create dependency update PR
        if: steps.check-updates.outputs.updates-available == 'true' && github.event.inputs.update_type == 'update'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "🔄 Automated Dependency Updates"
          body: |
            ## Automated Dependency Updates

            This PR updates outdated R package dependencies.

            ### Changes:
            - Updated ${{ steps.check-updates.outputs.outdated-count }} packages
            - Ran security vulnerability checks
            - Updated renv.lock file

            ### Testing:
            - All existing tests should pass
            - CI/CD workflows will validate changes

            ### Review Checklist:
            - [ ] All tests pass
            - [ ] No breaking changes
            - [ ] Documentation updated if needed
          branch: automated/dependency-updates
          delete-branch: true

      - name: Create security alert (if vulnerabilities found)
        if: steps.security-scan.outputs.security-issues == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Security Vulnerabilities Detected',
              body: 'Automated dependency scan found potential security vulnerabilities. Please review and update affected packages.',
              labels: ['security', 'dependencies', 'urgent']
            })

  dependency-report:
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Generate dependency report
        run: |
          echo "## 📊 Dependency Management Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "**Run Type:** ${{ github.event.inputs.update_type || 'scheduled' }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Results:" >> $GITHUB_STEP_SUMMARY
          echo "- Updates Available: ${{ steps.check-updates.outputs.updates-available == 'true' && 'Yes' || 'No' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Security Issues: ${{ steps.security-scan.outputs.security-issues == 'true' && 'Found' || 'None' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Packages Checked: ${{ steps.check-updates.outputs.outdated-count || '0' }}" >> $GITHUB_STEP_SUMMARY
